### ISSUE TITLE
Add option to leave out hostname from path in git get

### ISSUE THREAD

**Issue by Floppy** [grdl/git-get#3]
This is a great tool, thank you! I would suggest that sometimes the hostname is redundant in the tree structure, and it might be nice to have an option to ignore it. So instead you'd just have `<root>/<user>/<repo>` rather than `<root>/<host>/<user>/<repo>`

**Comment by grdl** [comment]
Thanks! I was thinking about something similar. If a tree node doesn't have any siblings, it won't be added as a new node but as a suffix to its parent.

So instead of:
```
/my/repos
  - github.com
    - user1
      - repo1
    - user2
      - repo2
```

it would show:
```
/my/repos/github.com
    - user1
      - repo1
    - user2
      - repo2
```

Does it make sense? If so, I'll add it next week.

**Comment by Floppy** [comment]
That makes sense in the tree view, I was thinking for `git get` when actually checking out the repositories.
