### ISSUE TITLE
git get leaves behind empty folders if it fails

### ISSUE THREAD

**Issue by wallrj** [grdl/git-get#9]
I ran `./get github.com/grdl/git-get` which failed because I forgot the `https://`, but it left behind a bunch of empty folders.

```
richard   master  …  github.com  grdl  git-get  ./get github.com/grdl/git-get
Cloning into '/home/richard/repositories/github.com/github.com/grdl/git-get'...
remote: Not Found
fatal: repository 'https://github.com/github.com/grdl/git-get/' not found
Error: "git clone https://github.com/github.com/grdl/git-get /home/richard/repositories/github.com/github.com/grdl/git-get": exit status 128


 richard   master  …  github.com  grdl  git-get  tree ~/repositories
/home/richard/repositories
└── github.com
    └── github.com
        └── grdl

3 directories, 0 files

```

I think it'd be nice to delete those if the command fails.
Maybe it could `git clone ... target/directory.tmpXXXX  and then rename that after the command succeeds and delete it if the command fails.

**Comment by grdl** [comment]
Fixed in [v0.3.0](https://github.com/grdl/git-get/releases/tag/v0.3.0).
